import '../../../domain/entities/faq.dart';

List<FaqCategory> faqCategoriesForLanguage(String languageCode) {
  return languageCode == 'am' ? _faqAmharic : _faqEnglish;
}

const _faqEnglish = [
  FaqCategory(
    name: 'Getting Started',
    items: [
      FaqItem(
        question: 'How do I create an account?',
        answer:
            'Tap "Sign Up" on the login screen. Enter your full name, email address, phone number (optional), and create a strong password (minimum 8 characters, one uppercase letter and one number). After submitting, you\'ll receive a verification email. Click the link to activate your account, then log in.',
      ),
      FaqItem(
        question: 'I forgot my password. How can I reset it?',
        answer:
            'On the login screen, tap "Forgot Password". Enter your registered email address. You will receive a reset code by email. Enter the code on the reset screen and set a new password.',
      ),
      FaqItem(
        question: 'Can I log in with my Google or Facebook account?',
        answer:
            'Currently, EduConnect supports only email/password login. We plan to add social login in a future update.',
      ),
    ],
  ),
  FaqCategory(
    name: 'Courses & Learning',
    items: [
      FaqItem(
        question: 'How do I find courses that interest me?',
        answer:
            'Use the Browse tab. Search by keywords and filter by category, level, price, and rating. Personalized recommendations appear on the Home screen from the EduConnect recommendation service.',
      ),
      FaqItem(
        question: 'What is the difference between free and paid courses?',
        answer:
            'Free courses can be enrolled immediately with no payment. Paid courses require purchase via the demo payment gateway (Chapa/Telebirr integration planned). Both provide access to lessons, assessments, and certificates upon completion.',
      ),
      FaqItem(
        question: 'How do I enroll in a course?',
        answer:
            'Open the course detail page. If free, tap "Enroll Now". If paid, tap "Add to Cart" or buy from the cart. After successful payment, the course appears in My Courses.',
      ),
      FaqItem(
        question: 'Can I preview course content before enrolling?',
        answer:
            'Yes. On the course detail page you can view the full curriculum and preview lessons marked as preview when available.',
      ),
      FaqItem(
        question: 'What types of learning materials are available?',
        answer:
            'Video lessons (YouTube embedded), live classes (external meeting links), articles (rich HTML), quizzes and assignments, and downloadable resources where provided.',
      ),
      FaqItem(
        question: 'How is my progress tracked?',
        answer:
            'Progress is saved on the EduConnect server when you mark lessons complete. Your percentage appears on course cards and the course progress screen.',
      ),
      FaqItem(
        question: 'Can I watch videos offline?',
        answer:
            'Offline lesson downloads are planned. You can replay cached content when offline if it was previously loaded. Use Settings → Download over WiFi only to control downloads.',
      ),
    ],
  ),
  FaqCategory(
    name: 'Assessments & Certificates',
    items: [
      FaqItem(
        question: 'Where can I see my upcoming assessments?',
        answer:
            'Open a course from My Courses and view assessments on the progress screen, or go to Profile → Assessments and choose your course.',
      ),
      FaqItem(
        question: 'What types of questions are on quizzes?',
        answer:
            'The platform supports multiple choice and short answer questions. Your instructor may add more types over time.',
      ),
      FaqItem(
        question: 'Can I retake an assessment if I fail?',
        answer:
            'If retakes are allowed, you will see a Retake option on the result screen. Maximum attempts are set by the instructor and shown before you start.',
      ),
      FaqItem(
        question: 'How do I earn a certificate?',
        answer:
            'Complete all lessons and pass required assessments. When eligible, issue your certificate from the course or Certificates section. The server generates a verifiable PDF.',
      ),
      FaqItem(
        question: 'How can I verify my certificate?',
        answer:
            'Each certificate has a unique verification code. Scan the QR code or visit https://verify.educonnect.et/[code] to confirm authenticity.',
      ),
      FaqItem(
        question: 'Can I download and share my certificate?',
        answer:
            'Yes. Open the certificate and tap Download PDF. The file is generated by the backend. Use Share to send it via email, WhatsApp, or other apps.',
      ),
    ],
  ),
  FaqCategory(
    name: 'Shopping Cart & Payments',
    items: [
      FaqItem(
        question: 'How do I add a paid course to my cart?',
        answer:
            'On the course detail page, tap "Add to Cart". You can add multiple paid courses and checkout together. Each course is processed as a separate payment on the server.',
      ),
      FaqItem(
        question: 'What payment methods are accepted?',
        answer:
            'The app uses the EduConnect demo payment gateway during development. Production builds will support Chapa (cards, bank transfer) and Telebirr.',
      ),
      FaqItem(
        question: 'Is my payment information secure?',
        answer:
            'Payments are processed by the payment provider. EduConnect does not store card or mobile money credentials—only payment confirmation from the API.',
      ),
      FaqItem(
        question: 'Can I get a refund for a course?',
        answer:
            'Refund policies depend on the institution offering the course. Check the course description or contact support@educonnect.et within 7 days if you completed less than 20% of the course.',
      ),
    ],
  ),
  FaqCategory(
    name: 'Offline Mode & Technical',
    items: [
      FaqItem(
        question: 'Does the app work without internet?',
        answer:
            'Some features need internet: login, new content, live classes, and submitting assessments. Cached catalog and saved answers may be available offline where implemented.',
      ),
      FaqItem(
        question: 'How do I clear my app cache?',
        answer:
            'Go to Profile → Settings → Clear Cache. This removes temporary files but not your account, enrollments, or downloaded certificates.',
      ),
      FaqItem(
        question: 'The app is slow or crashing. What should I do?',
        answer:
            'Close and reopen the app, clear cache, update to the latest version, and restart your device. Contact support via Profile → Help & Support if issues continue.',
      ),
      FaqItem(
        question: 'How much storage space does the app use?',
        answer:
            'The app is about 50 MB. Downloaded PDFs and media add more space depending on how many courses you save offline.',
      ),
    ],
  ),
  FaqCategory(
    name: 'Account & Privacy',
    items: [
      FaqItem(
        question: 'How do I change my profile picture?',
        answer:
            'Go to Profile → Edit Profile and tap the camera icon on your avatar. Choose a photo from your gallery (stored on your device until a server profile API is available).',
      ),
      FaqItem(
        question: 'How do I update my email or phone number?',
        answer:
            'Update phone and bio in Profile → Edit Profile. Email changes require support verification—contact support@educonnect.et.',
      ),
      FaqItem(
        question: 'Is my data shared with third parties?',
        answer:
            'EduConnect does not sell personal data. We share only what is needed for payments and certificate verification. See Privacy Policy in Settings.',
      ),
      FaqItem(
        question: 'How do I delete my account?',
        answer:
            'Account deletion via the app is coming soon. Email support@educonnect.et to request permanent deletion of your account and data.',
      ),
    ],
  ),
  FaqCategory(
    name: 'Support & Troubleshooting',
    items: [
      FaqItem(
        question: 'How can I contact support?',
        answer:
            'Profile → Help & Support, or email support@educonnect.et. Phone support: +251-XXX-XXXX (weekdays 9 AM – 5 PM).',
      ),
      FaqItem(
        question: 'A video won\'t play. What can I do?',
        answer:
            'Check your internet connection and try again. If the lesson uses YouTube, ensure you are not blocking embedded players. Report broken links via course support.',
      ),
      FaqItem(
        question: 'I completed a course but didn\'t receive my certificate.',
        answer:
            'Confirm 100% lesson progress and passed assessments. Wait a few minutes, then use Request/Issue certificate on the progress screen or contact support.',
      ),
      FaqItem(
        question: 'The app displays "Session expired" repeatedly.',
        answer:
            'Log out and sign in again. If it continues, clear cache in Settings or reinstall the app. Ensure your device date and time are correct.',
      ),
    ],
  ),
];

/// Shorter Amharic headings with English answers for key flows (expand over time).
const _faqAmharic = [
  FaqCategory(
    name: 'መጀመሪያ',
    items: [
      FaqItem(
        question: 'መለያ እንዴት እፈጥራለሁ?',
        answer:
            'በመግቢያ ማያ ገጽ "Sign Up" ይጫኑ። ሙሉ ስም፣ ኢሜይል፣ ስልክ (አማራጭ) እና የሚያስፈልገው የይለፍ ቃል ያስገቡ። ኢሜይል ማረጋገጫ ካገኙ በኋላ ይግቡ።',
      ),
      FaqItem(
        question: 'የይለፍ ቃል ረሳሁ። እንዴት እቀይራለሁ?',
        answer:
            '"Forgot Password" ይጫኑ፣ ኢሜይልዎን ያስገቡ፣ ኮድ ይደርስዎታል፣ አዲስ የይለፍ ቃል ያስቀምጡ።',
      ),
    ],
  ),
  FaqCategory(
    name: 'ኮርሶች እና ትምህርት',
    items: [
      FaqItem(
        question: 'ኮርሶችን እንዴት አገኛለሁ?',
        answer: 'የታች አሰሳ → Browse ይጠቀሙ። በቤት ገጽ ምክር የተሰጡ ኮርሶች ይታያሉ።',
      ),
      FaqItem(
        question: 'በካርት ብዙ ኮርሶች መግዛት እችላለሁ?',
        answer: 'አዎ። ብዙ ክፍያ የሚጠዩ ኮርሶችን ወደ ካርት ያክሉና በአንድ ጊዜ checkout ያድርጉ።',
      ),
    ],
  ),
  FaqCategory(
    name: 'ድጋፍ',
    items: [
      FaqItem(
        question: 'ድጋፍ እንዴት አገኛለሁ?',
        answer: 'መገለጫ → Help & Support ወይም support@educonnect.et',
      ),
    ],
  ),
];
